"""
MILGRAU - Level 1 Visualization: LIRACOS

LIRACOS (LIdar RAnge COrrected Signal) renders Level 1 range-corrected
signal products generated by LIPANCORA. The script reads *_level1_rcs.nc
files, converts altitude to kilometers for plotting, and delegates all
figure construction to functions.viz_utils.


@author: Luisa Mello, Fábio J. S. Lopes, Alexandre C. Yoshida and Alexandre Cacheffo
"""

from __future__ import annotations

import gc
import logging
import traceback
import warnings
from pathlib import Path
from typing import Any

import xarray as xr
from matplotlib import pyplot as plt

from functions.core_io import ensure_directories, load_config, setup_logger
from functions.viz_utils import plot_global_mean_rcs, plot_quicklook

warnings.filterwarnings("ignore", category=RuntimeWarning)


def _as_bool(value: Any, default: bool = False) -> bool:
    """
    Convert configuration values to bool safely.

    YAML parsers usually return real booleans, but this helper also accepts
    common string representations so the script is robust to hand-edited files.
    """
    if isinstance(value, bool):
        return value
    if isinstance(value, str):
        return value.strip().lower() in {"true", "1", "yes", "y"}
    if value is None:
        return default
    return bool(value)


def _get_visualization_channels(config: dict[str, Any]) -> list[str]:
    """
    Return the list of Level 1 channels requested for quicklook rendering.

    Duplicate channels are removed while preserving the order defined in YAML.
    This avoids rendering the same plot twice when a channel is accidentally
    repeated in config["visualization"]["channels_to_plot"].
    """
    channels = config.get("visualization", {}).get("channels_to_plot", []) or []

    unique_channels: list[str] = []
    seen: set[str] = set()

    for channel in channels:
        channel_name = str(channel)
        if channel_name not in seen:
            unique_channels.append(channel_name)
            seen.add(channel_name)

    return unique_channels


def _get_altitude_ranges_km(config: dict[str, Any]) -> list[float]:
    """
    Return configured altitude limits in kilometers.

    Invalid values are ignored. If the configuration is missing or fully
    invalid, a conservative default is used.
    """
    raw_ranges = config.get("visualization", {}).get("altitude_ranges_km", [5, 15, 30])
    altitude_ranges: list[float] = []

    for value in raw_ranges:
        try:
            altitude_km = float(value)
        except (TypeError, ValueError):
            continue

        if altitude_km > 0:
            altitude_ranges.append(altitude_km)

    return altitude_ranges or [5.0, 15.0, 30.0]


def _prepare_level1_for_visualization(ds: xr.Dataset) -> xr.Dataset:
    """
    Return a plotting-ready copy/view of a Level 1 dataset.

    Level 1 NetCDF files store altitude in meters because that is the natural
    unit for physical processing. LIRACOS plots are labeled in kilometers, so
    the altitude coordinate is converted here before any plotting call.
    """
    if "altitude" not in ds.coords:
        raise ValueError("Level 1 dataset does not contain an 'altitude' coordinate.")

    max_altitude = float(ds["altitude"].max().values)

    # Avoid double conversion if a caller already provided altitude in km.
    if max_altitude > 100.0:
        ds = ds.assign_coords(altitude=ds["altitude"] / 1000.0)

    ds["altitude"].attrs["units"] = "km"
    ds["altitude"].attrs["long_name"] = "Altitude above ground level"
    return ds


def _extract_level1_boundaries(ds: xr.Dataset) -> tuple[xr.DataArray | None, float, float]:
    """
    Extract PBL and tropopause metadata used as overlays in Level 1 plots.

    Returns
    -------
    pbl_da:
        Time series of PBL height in km, when available.
    cpt_km:
        Cold-point tropopause height in km, or -999.0 when unavailable.
    lrt_km:
        Lapse-rate tropopause height in km, or -999.0 when unavailable.
    """
    pbl_da = ds["PBL_Height_km"] if "PBL_Height_km" in ds else None
    cpt_km = float(ds.attrs.get("tropopause_cpt_km", -999.0))
    lrt_km = float(ds.attrs.get("tropopause_lrt_km", -999.0))
    return pbl_da, cpt_km, lrt_km


def process_single_nc(
    args: tuple[str | Path, dict[str, Any], str | Path, logging.Logger],
) -> str:
    """
    Render all Level 1 quicklooks for one NetCDF file.

    Parameters
    ----------
    args:
        Tuple containing the NetCDF path, configuration dictionary, project
        root directory, and logger. A tuple keeps this function compatible with
        future multiprocessing use.

    Returns
    -------
    str
        Human-readable processing status used by the main loop.
    """
    nc_file_path, config, root_dir, logger = args
    nc_file = Path(nc_file_path)
    root_path = Path(root_dir)

    try:
        file_name_prefix = nc_file.name.replace("_level1_rcs.nc", "")
        output_folder = nc_file.parent / "quicklooks"
        ensure_directories(output_folder)

        incremental = _as_bool(config.get("processing", {}).get("incremental", False))
        check_file = output_folder / f"GlobalMeanRCS_{file_name_prefix}.webp"

        if incremental and check_file.exists():
            return f"[SKIPPED] Plots already exist for: {file_name_prefix}"

        logger.info(f"[{file_name_prefix}] Loading Level 1 data and preparing axes...")

        with xr.open_dataset(nc_file) as ds:
            ds.load()
            ds = _prepare_level1_for_visualization(ds)

            pbl_da, cpt_km, lrt_km = _extract_level1_boundaries(ds)
            channels_to_plot = _get_visualization_channels(config)
            altitude_ranges = _get_altitude_ranges_km(config)

            logger.info(
                f"[{file_name_prefix}] Rendering quicklooks for "
                f"{len(channels_to_plot)} configured channels."
            )

            available_channels = {str(channel) for channel in ds.channel.values}

            for channel_name in channels_to_plot:
                if channel_name not in available_channels:
                    logger.warning(f"[{file_name_prefix}] Channel not found, skipping: {channel_name}")
                    continue

                rc_signal = ds["corrected_signal"].sel(channel=channel_name)
                rc_error = ds["corrected_signal_error"].sel(channel=channel_name)

                for max_altitude in altitude_ranges:
                    sig_slice = rc_signal.sel(altitude=slice(0, max_altitude))
                    err_slice = rc_error.sel(altitude=slice(0, max_altitude))

                    if sig_slice.size == 0:
                        logger.warning(
                            f"[{file_name_prefix}] Empty altitude slice for "
                            f"{channel_name} up to {max_altitude} km."
                        )
                        continue

                    plot_quicklook(
                        data_slice=sig_slice,
                        error_slice=err_slice,
                        max_altitude=max_altitude,
                        channel_name=channel_name,
                        ds=ds,
                        output_folder=str(output_folder),
                        file_name_prefix=file_name_prefix,
                        config=config,
                        root_dir=str(root_path),
                        pbl_da=pbl_da,
                        cpt_km=cpt_km,
                        lrt_km=lrt_km,
                    )

                    # Explicit cleanup helps in long rendering batches.
                    del sig_slice, err_slice
                    plt.close("all")
                    gc.collect()

            logger.info(f"[{file_name_prefix}] Generating global mean RCS profile...")
            plot_global_mean_rcs(
                ds=ds,
                output_folder=str(output_folder),
                file_name_prefix=file_name_prefix,
                config=config,
                root_dir=str(root_path),
            )

        plt.close("all")
        gc.collect()

        return f"[OK] All plots generated for {file_name_prefix}"

    except Exception:
        return f"[FAILED] Error plotting {nc_file.name}:\n{traceback.format_exc()}"


def process_all_level1_files(
    config: dict[str, Any],
    logger: logging.Logger,
    root_dir: str | Path | None = None,
) -> None:
    """
    Discover and render all Level 1 NetCDF files under processed_data.

    This function exists so the script can be imported and called from tests or
    notebooks without executing the __main__ block.
    """
    root_path = Path.cwd() if root_dir is None else Path(root_dir)
    base_data_folder = root_path / config["directories"]["processed_data"]
    nc_files = sorted(base_data_folder.rglob("*_level1_rcs.nc"))

    if not nc_files:
        logger.warning(f"No Level 1 NetCDF data found in '{base_data_folder}'. Exiting.")
        return

    logger.info(f"Found {len(nc_files)} Level 1 files.")

    for nc_file in nc_files:
        result = process_single_nc((nc_file, config, root_path, logger))
        if "[OK]" in result or "[SKIPPED]" in result:
            logger.info(result)
        else:
            logger.error(result)


def main() -> None:
    """Command-line entry point for LIRACOS."""
    config = load_config()
    logger = setup_logger("LIRACOS", config["directories"]["log_dir"])
    logger.info("=== Starting MILGRAU LIRACOS rendering (Level 1 Visualization) ===")

    process_all_level1_files(config=config, logger=logger, root_dir=Path.cwd())

    logger.info("=== LIRACOS processing finished! ===")


if __name__ == "__main__":
    main()
